SELECT a.ID, 
    (CASE
        WHEN b.r <= (SELECT COUNT(*) FROM ECOLI_DATA) / 4 THEN "LOW"
        WHEN b.r <= (SELECT COUNT(*) FROM ECOLI_DATA) / 4 * 2 THEN "MEDIUM"
        WHEN b.r <= (SELECT COUNT(*) FROM ECOLI_DATA) / 4 * 3 THEN "HIGH"
        ELSE "CRITICAL"
     END
    ) AS COLONY_NAME
FROM ECOLI_DATA a
LEFT OUTER JOIN
(SELECT ID, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY) AS r
FROM ECOLI_DATA
ORDER BY SIZE_OF_COLONY) b
ON a.ID = b.ID
ORDER BY a.ID;