SELECT a.USER_ID, a.NICKNAME, CONCAT(a.CITY,' ', a.STREET_ADDRESS1,' ', a.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTR(a.TLNO,1,3),'-',SUBSTR(a.TLNO,4,4),'-',SUBSTR(a.TLNO,8,4)) as 전화번호
FROM USED_GOODS_USER a
RIGHT OUTER JOIN
    (SELECT WRITER_ID, count(*)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING 3 <= COUNT(*)) b
ON a.USER_ID = b.WRITER_ID
ORDER BY a.USER_ID desc