-- 코드를 입력하세요
SELECT t2.TITLE, t1.BOARD_ID, t1.REPLY_ID, t1.WRITER_ID, t1.CONTENTS, DATE_FORMAT(t1.CREATED_DATE,'%Y-%m-%d') AS `CREATED_DATE`
FROM USED_GOODS_REPLY t1 LEFT OUTER JOIN USED_GOODS_BOARD t2
ON t1.BOARD_ID = t2.BOARD_ID
WHERE t2.CREATED_DATE < '2022-11-01' AND '2022-10-01' <= t2.CREATED_DATE
ORDER BY t1.CREATED_DATE, t2.TITLE;