select YEAR(a.DIFFERENTIATION_DATE) YEAR, (m-a.SIZE_OF_COLONY) YEAR_DEV, a.ID from ECOLI_DATA a
left outer join (
    SELECT YEAR(DIFFERENTIATION_DATE) y, max(SIZE_OF_COLONY) m
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) b
ON YEAR(a.DIFFERENTIATION_DATE) = b.y
ORDER BY YEAR, YEAR_DEV, ID