SELECT c.ID, d.FISH_NAME, d.LENGTH
FROM FISH_INFO c
LEFT OUTER JOIN
    (
    SELECT a.FISH_TYPE, a.FISH_NAME, b.LENGTH
    FROM FISH_NAME_INFO a
    LEFT OUTER JOIN
        (SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE) b
        ON a.FISH_TYPE = b.FISH_TYPE
        ) d
ON d.FISH_TYPE = c.FISH_TYPE
WHERE c.LENGTH = d.LENGTH
ORDER BY c.ID