SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING 33 <= 
    AVG(
    CASE
    WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH
    END
    )
ORDER BY FISH_TYPE